# This is a basic workflow to help you get started with Actions

name: build image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout my code
        uses: actions/checkout@v2

      # Setup java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      # setup docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: prosanteconnect
          password: ${{ secrets.PSC_DOCKERHUB_TOKEN }}
      
      # Build and push from current repository (Dockerfile). This pushes the pscextract-base image to dockerhub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: prosanteconnect/pscextract-base:latest
          
      # Build an image tarball with Maven
      - name: Build with Maven
        run: mvn -B compile jib:buildTar --file pom.xml
      
      # This builds and saves your image to target/jib-image.tar, which you can load into docker with:
      - name: Build with Docker
        run: docker load --input target/jib-image.tar
        
      # Push pscextract
      - name: Push with Docker
        run: docker push prosanteconnect/pscextract
